import Navbar from "@/components/Navbar.jsx";
import Footer from "@/components/Footer.jsx";
import "./globals.css";
import { CartProvider } from "@/context/CartContext.jsx"; // ✅ Import the provider

export const metadata = {
  title: "E-Store",
  description: "Generated by E-Store",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col">
        {/* ✅ Wrap the whole app with CartProvider */}
        <CartProvider>
          {/* Navbar */}
          <Navbar />

          {/* Main Content */}
          <main className="flex-1">{children}</main>

          {/* Footer */}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
